### ISSUE TITLE
Virustotal is false positive?

### ISSUE THREAD

**Issue by iuriimattos2** [phonowell/genshin-impact-script#142]
https://www.virustotal.com/gui/file/4409e009cb3e9a090a089ed2cf16beb37ae8bb56ec811a6fafeaa8020812b444

**Comment by phonowell** [comment]
Hi there, sorry to hear about the false positive on VirusTotal. Unfortunately, AHK scripts are often flagged as potential threats because they allow users to automate tasks on their computer. There's not much we can do to fix this, but if you're still uneasy you can always choose not to use the script. Alternatively, you can check out the source code yourself since the project is open source. Hope this helps, and happy gaming!

**Comment by phonowell** [comment]
Hi there, sorry to hear about the false positive on VirusTotal. Unfortunately, AHK scripts are often flagged as potential threats because they allow users to automate tasks on their computer. There's not much we can do to fix this, but if you're still uneasy you can always choose not to use the script. Alternatively, you can check out the source code yourself since the project is open source. Hope this helps, and happy gaming!
