### ISSUE TITLE
Banning!?

### ISSUE THREAD

**Issue by satancurls** [phonowell/genshin-impact-script#16]
**Hello! 👻**
Do you think there is any possibility of being banned?
I don't think so but it's always good to ask.

**Comment by phonowell** [comment]
If you personally tell mihoyo that you are using a script, I think you have a high probability of being banned then.
But if you only use it secretly, as far as I know, no one has had problems with it.

- AHK is widely used in non-game environments, so it's unlikely that the process will be targeted.
- The script itself does not come with any cheat function, all operations are manually reproducible; your data is exactly the same as other players.
- Mihoyo doesn't have enough detection ability right now (both of time and technology).

But I think the potential risk of being banned is always there, which is why you should not discuss the script in public.

**Comment by krrr** [comment]
它们还是有检测方式的，游戏驱动可以读任意进程的内存，然后扫描脚本的内存进行特征码匹配
