### ISSUE TITLE
ITS THE DATA

### ISSUE THREAD

**Issue by sunxxin** [phonowell/genshin-impact-script#175]
it glitchs a alot for mw

**Comment by phonowell** [comment]
Hello,

I'm not quite sure what you're trying to express. Could you please provide more information or context? If you're experiencing a problem, it would be helpful to describe it in more detail so that I can better understand and assist you.

It's important to remember that posting nonsensical or disruptive comments is not helpful to anyone. If you're just trying to play a prank or cause trouble, please stop. Such behavior is not acceptable and may result in further action being taken.

Thank you for your cooperation. Let's work together to make this a positive and productive community.
