### ISSUE TITLE
how to run this script?

### ISSUE THREAD

**Issue by BLANK0104** [phonowell/genshin-impact-script#202]
I have downloaded the zip file and also read the readme but I still don't know how to use this tool or more precisely, what file am i supposed to run once the game begins?
In the guide from readme, it says "simply launch the script" but i dont know which file is suppposed to be the script or what file should be run.

**Comment by phonowell** [comment]
At the outset, may I confirm if you are familiar with GitHub? Based on your description, it appears that you have downloaded the source code of the project. However, unfortunately, the source code is of no use to you unless you intend to participate in its development. What you require is the "Release" link on the right-hand side of the page, which is not prominently displayed, instead of the conspicuous green button on the page. As GitHub is primarily aimed at developers, it may not be very user-friendly for non-developers. I hope this information is helpful to you.

**Comment by BLANK0104** [comment]
i got it now..thanks...it works amazingly well
