### ISSUE TITLE
A issue

### ISSUE THREAD

**Issue by satancurls** [phonowell/genshin-impact-script#29]
Hey! 👻 ~ It's me again, hehehe.
Sometimes when I use the right button, it opens the menu for some reason instead of running...

**Comment by phonowell** [comment]
In recent versions `right click` has a new function: close menu (similar to pressing `esc`)
So, in some scenarios the problem you describe can occur, for example just exiting from the menu, five-star characters using `Q` or too close to the edge of the map (and this one was fixed in `0.0.12`)
If you don't like this feature, you can set `enableQuickDialog = 0` in your `config.ini` to turn it off
