### ISSUE TITLE
About recording and playing

### ISSUE THREAD

**Issue by DerksonVHM** [phonowell/genshin-impact-script#32]
I don't know if i've done something wrong, but when i downloaded the script and tried to record some simple movements with f10+f11, the commands inside the game were not working, but if i started to play what i've recorded and opened the Opera GX tab, the commands would go there, any suggestion?

**Comment by phonowell** [comment]
First you need to check the `region/process` option in your `config.ini`, its default value is `YuanShen.exe`, but if you are not in `Sky Island` or `World Tree` server, you should change it to `GenshinImpact.exe`, otherwise the script will not work

At first this script didn't consider that much, I will develop a separate version for different regions in the next version

**Comment by DerksonVHM** [comment]
I've changed the name on config,ini already, i'll test again today to make sure if i wasn't doing something wrong. By the way, the recorded action is stored to be used at anytime i want or something else?

**Comment by phonowell** [comment]
Pretty much what you'd expect, but it only records some of the combat-related keyboard keys, so you can't use it for big world running or playing instrument for now

**Comment by DerksonVHM** [comment]
Got it, thanks. Keep up with the good work =)
