### ISSUE TITLE
Character tactics key recognition error

### ISSUE THREAD

**Issue by Qulox** [phonowell/genshin-impact-script#53]
If I just press the characters keys once (1, 2, 3, 4) most of the time the character just uses the tactic of the previous character instead of loading the on-long-press tactic assigned to them.
 If I press the character key twice it loads correctly.

For example:
I have assigned `[fischl] on-long-press = a, 100, a, tt, e` but if I press the key only once I get: `e~, a` that is Diona's tactics that I used before selecting Fischl.

Win10.
Script v20
1080p borderless-fullscreen on 4k TV.
config.ini :
```
[basic]

; 性能
; high | medium | low
performance = medium

; 地区
; CN | EN
region = EN

[feature]

; 启用改良跳跃
; 0 | 1
enable-better-jump = 1

; 启用技能计时器
; 0 | 1
enable-skill-timer = 1

; 启用快速拾取
; 0 | 1
enable-fast-pickup = 1

; 启用快速事件
; 0 | 1
enable-quick-event = 1

[amber]
on-long-press = a~, 150

[diona]
on-long-press = e~, a

[eula]
on-long-press = a, e

[fischl]
on-long-press = a, 100, a, tt, e

[ganyu]
on-long-press = a~, a

[hu_tao]
on-long-press = !@e, a, e, @e, 300; a~, 150, j, 50

[keqing]
on-long-press = a, ee

[klee]
on-long-press = a, a~

[ningguang]
on-long-press = a, 700, a, 400, a~, 500, e

[venti]
on-long-press = @m, a, 100, a, tt; a, a~

[xingqiu]
on-long-press = a, ee

[zhongli]
on-long-press = a, e~
```

![GI](https://user-images.githubusercontent.com/15495523/129430281-6da2ef85-b8ea-4bb3-b469-95f4ea56d278.png)

**Comment by phonowell** [comment]
From the description, it looks like this failure is caused by a failed detection of character switching
You can confirm this by following these steps.
- The skill timer will add a small icon to the back of the current character
- Press the switch button only once, then use the E skill and watch for the icon to appear after the timer for the corresponding character
- If the icon appears on the previous character, then the script failed to detect the action
If you end up confirming that this is the reason for the failure, it may be due to a lack of computer performance.
In the meantime, I will extend the interval between script detections in the next release to improve stability.

**Comment by Qulox** [comment]
Network lag seem to be the case, sometimes when I use Xinqiu's E skill the icon appears on Eula. Also, when I played on a better connection the recognition when switching seemed to improve. Thanks
