### ISSUE TITLE
Suggestions.

### ISSUE THREAD

**Issue by TharakLoar** [phonowell/genshin-impact-script#54]
1. Would it be possible to make a toggle to skip the dialog that auto-stops once you are back on your character screen?
It is kind of a hassle even to just hold the button during some long dialogs...

2. Also, I found this script that seems to loot faster, here how it looks:

```
`#NoEnv`

SendMode Input
SetWorkingDir %A_ScriptDir%
#WinActivateForce
#singleInstance, Force
SetBatchLines -1
#MaxThreadsPerHotkey, 2
#IfWinActive ahk_exe GenshinImpact.exe

IniRead, HotkeyChoice, %A_WorkingDir%\config.ini, Hotkey, ActivationHotkey
Hotkey, %HotkeyChoice%, theHotKeyChoice, On






~$F12::
SUSPEND
PAUSE
return


theHotKeyChoice:
IniRead, LootHotkey, %A_WorkingDir%\config.ini, KeyBindSettings, LootHotkey
IniRead, DelayBetweenLoops, %A_WorkingDir%\config.ini, DelaySettings, DelayBetweenLoops



While GetKeyState(HotkeyChoice,"P")
{
	IfWinActive ahk_exe GenshinImpact.exe
	{
		Sleep, %DelayBetweenLoops%
		Send, {%LootHotkey% 3}
		Sleep, %DelayBetweenLoops%
		Send, {WheelDown 1}
		Sleep, %DelayBetweenLoops%
		if !GetKeyState(HotkeyChoice,"P")
		{
			break
		}
	}
	else
	{
		break
	}
}
return`
```

3. It would be nice to have a toggle so it uses the "chest finder" item when it's off cooldown, automatically. Or maybe when we are holding the F key.

Thank you for the great work! :)

**Comment by phonowell** [comment]
1. This feature may be added in the future, e.g. using the hotkey `Alt + F`.
2. The script pickup is deliberately set to be **not so fast**, in order to be similar to the human manual keystroke frequency, in order to avoid possible user behavior detection. In other words, the reason why it is not so fast is for security reasons
3. Considering the number of items bound to the `Z` key, this feature will be more difficult
